# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170905_0408'),
        ('users', '0005_auto_20170522_2224'),
    ]

    operations = [
    ]
