# Generated by Django 4.2.7 on 2025-04-24 17:52

import common.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
        ('common', '0001_initial'),
        ('chul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthworkercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.contact'),
        ),
        migrations.AddField(
            model_name='communityhealthworkercontact',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthworkercontact',
            name='health_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chul.communityhealthworker'),
        ),
        migrations.AddField(
            model_name='communityhealthworkercontact',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='health_unit',
            field=models.ForeignKey(help_text='The health unit the worker is in-charge of', on_delete=django.db.models.deletion.PROTECT, related_name='health_unit_workers', to='chul.communityhealthunit'),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthunitcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.contact'),
        ),
        migrations.AddField(
            model_name='communityhealthunitcontact',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthunitcontact',
            name='health_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chul.communityhealthunit'),
        ),
        migrations.AddField(
            model_name='communityhealthunitcontact',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='facility',
            field=models.ForeignKey(help_text='The facility on which the health unit is tied to.', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chul.status'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuupdatebuffer',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuupdatebuffer',
            name='health_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chul.communityhealthunit'),
        ),
        migrations.AddField(
            model_name='chuupdatebuffer',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuservicelink',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuservicelink',
            name='health_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='chul.communityhealthunit'),
        ),
        migrations.AddField(
            model_name='chuservicelink',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chul.chuservice'),
        ),
        migrations.AddField(
            model_name='chuservicelink',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuservice',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuservice',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churating',
            name='chu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chu_ratings', to='chul.communityhealthunit'),
        ),
        migrations.AddField(
            model_name='churating',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churating',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='communityhealthunitcontact',
            unique_together={('health_unit', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='communityhealthunit',
            unique_together={('name', 'facility')},
        ),
        migrations.AlterUniqueTogether(
            name='chuservicelink',
            unique_together={('health_unit', 'service')},
        ),
    ]
