# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 22:27
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0005_auto_20160520_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthunit',
            name='code',
            field=common.fields.SequenceField(blank=True, editable=False, help_text=b'A sequential number allocated to each chu', null=True, unique=True),
        ),
    ]
