# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0006_auto_20191023_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthunit',
            name='is_approved',
            field=models.NullBooleanField(help_text=b'Determines if a chu has been approved'),
        ),
    ]
