# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2024-05-30 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0007_auto_20191023_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityhealthunit',
            name='chas_present',
            field=models.PositiveIntegerField(default=0, help_text=b'Number of Community Health Assistants  in the CHU'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='chas_trained',
            field=models.PositiveIntegerField(default=0, help_text=b'Number of trained Community Health Assistants in the CHU'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='chcs_present',
            field=models.PositiveIntegerField(default=0, help_text=b'Number of Community Health Commitee Members in the CHU'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='chcs_trained',
            field=models.PositiveIntegerField(default=0, help_text=b'Number of trained Community Health Commitee Members in the CHU'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='chps_present',
            field=models.PositiveIntegerField(default=0, help_text=b'Number of Community Health Promoters in the CHU'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='chps_trained',
            field=models.PositiveIntegerField(default=0, help_text=b'Number of trained Community Health Promoters  in the CHU'),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='communityhealthworker',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
