# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-04-26 07:56
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0007_auto_20191023_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthunit',
            name='code',
            field=common.fields.SequenceField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='communityhealthunit',
            name='is_approved',
            field=models.NullBooleanField(),
        ),
    ]
