# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2024-05-30 09:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0008_addedmobileandemailtochuworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityhealthunit',
            name='has_iec_materials',
            field=models.BooleanField(default=False, help_text=b'Has Information, education and communication materials'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='has_iga',
            field=models.BooleanField(default=False, help_text=b'Has Income Generating Activities'),
        ),
        migrations.AddField(
            model_name='communityhealthunit',
            name='partners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, null=True, size=None),
        ),
    ]
