# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-04-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0008_auto_20230426_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthunit',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
