# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2024-05-30 09:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chul', '0009_addedpartners_iga_iec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthunit',
            name='partners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
