# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_auto_20170804_1022'),
        ('facilities', '0004_auto_20170522_2223'),
    ]

    operations = [
    ]
