# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_merge_20170806_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text=b'This is the unique name of the facility', max_length=100, unique=True),
        ),
    ]
