# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20170401_1011'),
        ('facilities', '0007_auto_20170907_1046'),
    ]

    operations = [
    ]
