# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_dhisauth'),
        ('facilities', '0008_merge_20170911_0851'),
    ]

    operations = [
    ]
