# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_merge_20190828_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhisauth',
            name='apiauthentication_ptr',
        ),
        migrations.DeleteModel(
            name='DhisAuth',
        ),
    ]
