# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_apiauthentication'),
        ('facilities', '0011_facility_approved_national_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhisAuth',
            fields=[
                ('apiauthentication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.ApiAuthentication')),
                ('oauth2_token_variable_name', models.CharField(default=b'api_oauth2_token', max_length=255)),
                ('type', models.CharField(default=b'DHIS2', max_length=255)),
            ],
            bases=('common.apiauthentication',),
        ),
    ]
