# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_dhisauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityapproval',
            name='is_national_approval',
            field=models.BooleanField(default=False, help_text=b'Approval of the facility at the national level'),
        ),
    ]
