# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_auto_20191021_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='approved_national_level',
            field=models.NullBooleanField(help_text=b'Has the facility been approved at the national level'),
        ),
    ]
