# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_auto_20191021_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reporting_in_dhis',
            field=models.BooleanField(default=False, help_text=b'A flag to indicate whether facility should have reporting in dhis'),
        ),
    ]
