# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_auto_20191021_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='approved',
            field=models.NullBooleanField(help_text=b'Has the facility been approved at the county level'),
        ),
    ]
