# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0021_auto_20211026_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='number_of_inpatient_beds',
            field=models.PositiveIntegerField(default=0, help_text=b'The number of General In-patient beds that a facility has e.g 0'),
        ),
    ]
