# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0022_auto_20230302_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityinfrastructure',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infrastructure', to='facilities.Infrastructure'),
        ),
        migrations.AlterField(
            model_name='facilityservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_id', to='facilities.Service'),
        ),
        migrations.AlterField(
            model_name='facilityspecialist',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciality', to='facilities.Speciality'),
        ),
    ]
