# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-23 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0024_facility_mydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='mydate',
        ),
        migrations.AddField(
            model_name='facility',
            name='date_updated',
            field=models.DateField(default=datetime.date.today, help_text=b'The date when the facility was approved or rejected'),
        ),
    ]
