# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-23 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0025_auto_20230323_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='date_updated',
        ),
    ]
