# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_remove_facility_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='update_date',
            field=models.DateTimeField(blank=True, help_text=b'Date the facility was updated', null=True),
        ),
    ]
