# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-23 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0027_facility_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='update_date',
            new_name='updating_date',
        ),
    ]
