# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0028_auto_20230323_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='updating_date',
        ),
        migrations.AddField(
            model_name='facility',
            name='approvalrejection_date',
            field=models.DateTimeField(blank=True, help_text=b'Date the facility was approved or rejected', null=True),
        ),
    ]
