# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2024-05-31 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0029_auto_20230327_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='new_born_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='number_of_eye_theatres',
            field=models.PositiveIntegerField(default=0, help_text=b'The number of eye theatres  that a facility has e.g 0'),
        ),
        migrations.AddField(
            model_name='facility',
            name='number_of_minor_theatres',
            field=models.PositiveIntegerField(default=0, help_text=b'The number of minor theatres  that a facility has e.g 0'),
        ),
        migrations.AddField(
            model_name='facility',
            name='out_reach_services',
            field=models.BooleanField(default=False),
        ),
    ]
