# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20170522_2223'),
        ('common', '0015_apiauthentication'),
    ]

    operations = [
    ]
