# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_auto_20190828_2112'),
        ('common', '0016_merge_20190828_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiAuthentication',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(default=b'NORMAL', max_length=255),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
