# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20190828_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'healthit', max_length=255)),
                ('password', models.CharField(default=b'Test1@hiskenya', max_length=255)),
                ('client_id', models.CharField(default=b'workforce17mfl@2018$', max_length=255)),
                ('client_secret', models.CharField(default=b'4b04e4e72-6542-3f78-f76b-37a3de0bdec', max_length=255)),
                ('server', models.CharField(default=b'https://test.hiskenya.org/kenya/', max_length=255)),
                ('session_key', models.CharField(default=b'dhis2_api_12904rs', max_length=255)),
            ],
        ),
    ]
