# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_apiauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthentication',
            name='client_id',
            field=models.CharField(default=b'102', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='client_secret',
            field=models.CharField(default=b'b79c67c5e-e06e-0e2c-72ce-99977ff65af', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='password',
            field=models.CharField(default=b'Admin123', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='server',
            field=models.CharField(default=b'https://testhis.uonbi.ac.ke/', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='username',
            field=models.CharField(default=b'stevewaweru', max_length=255),
        ),
    ]
