# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-12-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20191021_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthentication',
            name='client_secret',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='password',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='server',
            field=models.CharField(default=b'http://testhis.uonbi.ac.ke/', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='username',
            field=models.CharField(default=b'kmhfl_integration', max_length=255),
        ),
    ]
