# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-03-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20221205_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthentication',
            name='server',
            field=models.CharField(default=b'https://test.hiskenya.org/', max_length=255),
        ),
    ]
