# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2024-05-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20230302_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthentication',
            name='client_id',
            field=models.CharField(default=b'KMHFL', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='client_secret',
            field=models.CharField(default=b'65df9a025-31df-079d-14d5-a01e08ea947', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='server',
            field=models.CharField(default=b'https://hiskenya.org/', max_length=255),
        ),
    ]
