from django.urls import path

from .. import views

urlpatterns = (
    path('material/',
        views.FacilityExportMaterialListView.as_view(),
        name='material'),

    path('flattened_categories/',
        views.FlattenedCategories.as_view(),
        name='flattened_categories'),

    path('regulator_sync_update/<str:pk>/',
        views.RegulatorSyncUpdateView.as_view(),
        name='regulator_sync_update'),

    path('regulator_sync/<str:pk>/',
        views.RegulatorSyncDetailView.as_view(),
        name='regulator_sync_detail'),

    path('regulator_sync/',
        views.RegulatorSyncListView.as_view(),
        name='regulator_syncs_list'),

    path('option_group_with_options/',
        views.PostOptionGroupWithOptionsView.as_view(),
        name='post_option_group_with_options'),

    path('option_group_with_options/<str:pk>/',
        views.PostOptionGroupWithOptionsView.as_view(),
        name='delete_option_group_with_options'),

    path('level_change_reasons/',
        views.FacilityLevelChangeReasonListView.as_view(),
        name='facility_level_change_reasons_list'),
    path('level_change_reasons/<str:pk>/',
        views.FacilityLevelChangeReasonDetailView.as_view(),
        name='facility_level_change_reason_detail'),

    path('keph/', views.KephLevelListView.as_view(),
        name='keph_levels_list'),
    path('keph/<str:pk>/',
        views.KephLevelDetailView.as_view(),
        name='keph_level_detail'),

    path('officer_facade/',
        views.CustomFacilityOfficerView.as_view(),
        name='officer_facade_create'),

    path('officer_facade/<str:facility_id>/',
        views.CustomFacilityOfficerView.as_view(),
        name='officer_facade_list'),

    path('officer_facade/delete/<str:pk>/',
        views.CustomFacilityOfficerView.as_view(),
        name='officer_facade_delete'),

    path('facility_updates/',
        views.FacilityUpdatesListView.as_view(),
        name='facility_updatess_list'),
    path('facility_updates/<str:pk>/',
        views.FacilityUpdatesDetailView.as_view(),
        name='facility_updates_detail'),

    path('facility_unit_regulation/',
        views.FacilityUnitRegulationListView.as_view(),
        name='facility_unit_regulations_list'),
    path('facility_unit_regulation/<str:pk>/',
        views.FacilityUnitRegulationDetailView.as_view(),
        name='facility_unit_regulation_detail'),

    path('regulatory_body_users/',
        views.RegulatoryBodyUserListView.as_view(),
        name='regulatory_body_users_list'),
    path('regulatory_body_users/<str:pk>/',
        views.RegulatoryBodyUserDetailView.as_view(),
        name='regulatory_body_user_detail'),

    path('facility_officers/', views.FacilityOfficerListView.as_view(),
        name='facility_officers_list'),
    path('facility_officers/<str:pk>/',
        views.FacilityOfficerDetailView.as_view(),
        name='facility_officer_detail'),

    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),

    path('facility_correction_template/<str:pk>/',
        views.FacilityCorrectionTemplate.as_view(),
        name='facility_correction_template'),

    path('facility_inspection_report/<str:pk>/',
        views.FacilityInspectionReport.as_view(),
        name='facility_inspection_report'),

    path('facility_cover_report/<str:pk>/',
        views.FacilityCoverTemplate.as_view(),
        name='facility_cover_report'),

    path('facility_detail_report/<str:pk>/',
        views.FacilityDetailTemplate.as_view(),
        name='facility_detail_report'),

    path('regulating_body_contacts/',
        views.RegulatingBodyContactListView.as_view(),
        name='regulating_body_contacts_list'),
    path('regulating_body_contacts/<str:pk>/',
        views.RegulatingBodyContactDetailView.as_view(),
        name='regulating_body_contact_detail'),

    path('facility_upgrade/',
        views.FacilityUpgradeListView.as_view(),
        name='facility_upgrades_list'),
    path('facility_upgrade/<str:pk>/',
        views.FacilityUpgradeDetailView.as_view(),
        name='facility_upgrade_detail'),

    path('facility_operation_state/',
        views.FacilityOperationStateListView.as_view(),
        name='facility_operation_states_list'),
    path('facility_operation_state/<str:pk>/',
        views.FacilityOperationStateDetailView.as_view(),
        name='facility_operation_state_detail'),

    path('facility_approvals/', views.FacilityApprovalListView.as_view(),
        name='facility_approvals_list'),
    path('facility_approvals/<str:pk>/',
        views.FacilityApprovalDetailView.as_view(),
        name='facility_approval_detail'),

    path('facility_service_ratings/',
        views.FacilityServiceRatingListView.as_view(),
        name='facility_service_ratings_list'),
    path('facility_service_ratings/<str:pk>/',
        views.FacilityServiceRatingDetailView.as_view(),
        name='facility_service_rating_detail'),

    path('service_categories/',
        views.ServiceCategoryListView.as_view(),
        name='service_categories_list'),
    path('service_categories/<str:pk>/',
        views.ServiceCategoryDetailView.as_view(),
        name='service_category_detail'),

    path('services/', views.ServiceListView.as_view(), name='services_list'),
    path('services/<str:pk>/', views.ServiceDetailView.as_view(),
        name='service_detail'),

    path('options/', views.OptionListView.as_view(), name='options_list'),
    path('options/<str:pk>/', views.OptionDetailView.as_view(),
        name='option_detail'),

    path('facility_services/', views.FacilityServiceListView.as_view(),
        name='facility_services_list'),
    path('facility_services/<str:pk>/',
        views.FacilityServiceDetailView.as_view(),
        name='facility_service_detail'),

    # Specialities
    path('specialities/', views.SpecialityListView.as_view(), name='specialities_list'),
    path('specialities/<str:pk>/', views.SpecialityDetailView.as_view(),
        name='speciality_detail'),
    path('speciality_categories/', views.SpecialityCategoryListView.as_view(),
        name='speciality_categories_list'),
    path('speciality_categories/<str:pk>/',
        views.SpecialityCategoryDetailView.as_view(),
        name='speciality_categories_detail'),
    path('facility_specialists/', views.FacilitySpecialistListView.as_view(),
        name='facility_specialists_list'),
    path('facility_specialists/<str:pk>/',
        views.FacilitySpecialistDetailView.as_view(),
        name='facility_specialist_detail'),
    # Infrastructure
    path('infrastructure/', views.InfrastructureListView.as_view(), name='infrastructure_list'),
    path('infrastructure/<str:pk>/', views.InfrastructureDetailView.as_view(),
        name='infrastructure_detail'),
    path('infrastructure_categories/', views.InfrastructureCategoryListView.as_view(),
        name='facility_infrastructure_list'),
    path('infrastructure_categories/<str:pk>/',
        views.InfrastructureCategoryDetailView.as_view(),
        name='facility_infrastructure_detail'),
    path('facility_infrastructure/', views.FacilityInfrastructureListView.as_view(),
        name='facility_infrastructure_list'),
    path('facility_infrastructure/<str:pk>/',
        views.FacilityInfrastructureDetailView.as_view(),
        name='facility_infrastructure_detail'),
    # 

    path('facility_units/', views.FacilityUnitsListView.as_view(),
        name='facility_units_list'),
    path('facility_units/<str:pk>/',
        views.FacilityUnitDetailView.as_view(),
        name='facility_unit_detail'),

    path('regulating_bodies/', views.RegulatingBodyListView.as_view(),
        name='regulating_bodies_list'),
    path('regulating_bodies/<str:pk>/',
        views.RegulatingBodyDetailView.as_view(),
        name='regulating_body_detail'),

    path('facility_types/', views.FacilityTypeListView.as_view(),
        name='facility_types_list'),
    path('facility_types/<str:pk>/',
        views.FacilityTypeDetailView.as_view(),
        name='facility_type_detail'),
    path('facility_types_details/', views.FacilityTypeDetailsListView.as_view(),
        name='facility_types_details_list'),
        
    path('facility_status/', views.FacilityStatusListView.as_view(),
        name='facility_statuses_list'),
    path('facility_status/<str:pk>/',
        views.FacilityStatusDetailView.as_view(),
        name='facility_status_detail'),

    path('facility_admission_status/', views.FacilityAdmissionStatusListView.as_view(),
        name='facility_admission_statuses_list'),
    path('facility_admission_status/<str:pk>/',
        views.FacilityAdmissionStatusDetailView.as_view(),
        name='facility_admission_status_detail'),

    path('officer_contacts/', views.OfficerContactListView.as_view(),
        name='officer_contacts_list'),
    path('officer_contacts/<str:pk>/',
        views.OfficerContactDetailView.as_view(),
        name='officer_contact_detail'),

    path('job_titles/', views.JobTitleListView.as_view(),
        name='job_titles_list'),
    path('job_titles/<str:pk>/', views.JobTitleDetailView.as_view(),
        name='job_title_detail'),

    path('facility_regulation_status/',
        views.FacilityRegulationStatusListView.as_view(),
        name='facility_regulation_statuses_list'),
    path('facility_regulation_status/<str:pk>/',
        views.FacilityRegulationStatusDetailView.as_view(),
        name='facility_regulation_status_detail'),

    path('regulation_status/', views.RegulationStatusListView.as_view(),
        name='regulation_statuses_list'),
    path('regulation_status/<str:pk>/',
        views.RegulationStatusDetailView.as_view(),
        name='regulation_status_detail'),

    path('officers/', views.OfficerListView.as_view(),
        name='officers_in_charge_list'),
    path('officers_incharge/<str:pk>/',
        views.OfficerDetailView.as_view(),
        name='officer_detail'),

    path('owner_types/', views.OwnerTypeListView.as_view(),
        name='owner_types_list'),
    path('owner_types/<str:pk>/', views.OwnerTypeDetailView.as_view(),
        name='owner_type_detail'),

    path('owners/', views.OwnerListView.as_view(), name='owners_list'),
    path('owners/<str:pk>/', views.OwnerDetailView.as_view(),
        name='owner_detail'),

    path('contacts/', views.FacilityContactListView .as_view(),
        name='facility_contacts_list'),
    path('contacts/<str:pk>/',
        views.FacilityContactDetailView.as_view(),
        name='facility_contact_detail'),

    path('facilities_list/', views.FacilityListReadOnlyView.as_view(),
        name='facilities_read_list'),
    path('facilities/',
        views.FacilityListView.as_view(), name='facilities_list'),
    path('facilities/<str:pk>/', views.FacilityDetailView.as_view(),
        name='facility_detail'),

    path('option_groups/',
        views.OptionGroupListView.as_view(),
        name='option_groups_list'),
    path('option_groups/<str:pk>/',
        views.OptionGroupDetailView.as_view(),
        name='option_group_detail'),

    path('facility_depts/',
        views.FacilityDepartmentListView.as_view(),
        name='facility_depts_list'),
    path('facility_depts/<str:pk>/',
        views.FacilityDepartmentDetailView.as_view(),
        name='facility_depts_detail'),
)
