# Generated by Django 4.2.7 on 2025-04-24 17:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import mfl_gis.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrilldownView',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('county', models.PositiveIntegerField()),
                ('constituency', models.PositiveIntegerField()),
                ('ward', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'mfl_gis_drilldown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstituencyBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'constituency boundaries',
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CountyBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'county boundaries',
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='FacilityCoordinates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'facility coordinates',
                'verbose_name_plural': 'facility coordinates',
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
            bases=(mfl_gis.models.CoordinatesValidatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeoCodeMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(help_text='The name of the method.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the method', null=True)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='GeoCodeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(help_text='The name of the collecting organization', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short summary of the collecting organization', null=True)),
                ('abbreviation', models.CharField(blank=True, help_text='An acronym of the collecting or e.g SAM', max_length=10, null=True)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='WardBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'ward boundaries',
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the record has been retired?')),
                ('search', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
