# Generated by Django 4.2.7 on 2025-04-24 17:52

import common.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mfl_gis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('facilities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardboundary',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.ward'),
        ),
        migrations.AddField(
            model_name='wardboundary',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wardboundary',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocodesource',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocodesource',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocodemethod',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geocodemethod',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitycoordinates',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitycoordinates',
            name='facility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facility_coordinates_through', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='facilitycoordinates',
            name='method',
            field=models.ForeignKey(blank=True, help_text='Method used to obtain the geo codes. e.g taken with GPS device', null=True, on_delete=django.db.models.deletion.PROTECT, to='mfl_gis.geocodemethod'),
        ),
        migrations.AddField(
            model_name='facilitycoordinates',
            name='source',
            field=models.ForeignKey(blank=True, help_text='where the geo code came from', null=True, on_delete=django.db.models.deletion.PROTECT, to='mfl_gis.geocodesource'),
        ),
        migrations.AddField(
            model_name='facilitycoordinates',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countyboundary',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.county'),
        ),
        migrations.AddField(
            model_name='countyboundary',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countyboundary',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.constituency'),
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='created_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='updated_by',
            field=models.ForeignKey(default=common.models.base.get_default_system_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
