from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from .views import (
    ContactView,
    ContactDetailView,
    CountyView,
    CountyDetailView,
    CountySlimDetailView,
    ConstituencyView,
    ConstituencyDetailView,
    ConstituencySlimDetailView,
    WardView,
    WardDetailView,
    WardSlimDetailView,
    ContactTypeListView,
    ContactTypeDetailView,
    UserCountyView,
    UserCountyDetailView,
    UserContactListView,
    UserContactDetailView,
    TownListView,
    TownDetailView,
    PhysicalAddressView,
    PhysicalAddressDetailView,
    FilteringSummariesView,
    UserConstituencyDetailView,
    UserConstituencyListView,
    SubCountyDetailView,
    SubCountyListView,
    DocumentUploadListView,
    DocumentUploadDetailView,
    ErrorQueueDetailView,
    ErrorQueueListView,
    UserSubCountyDetailView,
    UserSubCountyListView,
    NotificationListView,
    NotificationDetailView
)

app_name = 'common'

urlpatterns = (
    path('notifications/',
        NotificationListView.as_view(),
        name='notifications_list'),
    path('notifications/<str:pk>/',
        NotificationDetailView.as_view(),
        name='notification_detail'),

    path('errors/',
        ErrorQueueListView.as_view(),
        name='error_queues_list'),
    path('errors/<str:pk>/',
        ErrorQueueDetailView.as_view(),
        name='error_queue_detail'),

    path('user_sub_counties/',
        UserSubCountyListView.as_view(),
        name='user_sub_counties_list'),
    path('user_sub_counties/<str:pk>/',
        UserSubCountyDetailView.as_view(),
        name='user_sub_county_detail'),

    path('sub_counties/',
        SubCountyListView.as_view(),
        name='sub_counties_list'),
    path('sub_counties/<str:pk>/',
        SubCountyDetailView.as_view(),
        name='sub_county_detail'),

    path('user_constituencies/',
        UserConstituencyListView.as_view(),
        name='user_constituencies_list'),
    path('user_constituencies/<str:pk>/',
        UserConstituencyDetailView.as_view(),
        name='user_constituency_detail'),

    path('contact_types/', ContactTypeListView.as_view(),
        name='contact_types_list'),
    path('contact_types/<str:pk>/', ContactTypeDetailView.as_view(),
        name='contact_type_detail'),

    path('user_contacts/', UserContactListView.as_view(),
        name='user_contacts_list'),
    path('user_contacts/<str:pk>/', UserContactDetailView.as_view(),
        name='user_contact_detail'),

    path('contacts/', ContactView.as_view(), name='contacts_list'),
    path('contacts/<str:pk>/', ContactDetailView.as_view(),
        name='contact_detail'),

    path('counties/',
        CountyView.as_view(),
        name='counties_list'),
    path('counties/<str:pk>/',
        cache_page(60*60*12)(CountyDetailView.as_view()),
        name='county_detail'),
    path('counties/slim_detail/<str:pk>/',
        cache_page(60*60*12)(CountySlimDetailView.as_view()),
        name='county_slim_detail'),

    path('user_counties/',
        UserCountyView.as_view(),
        name='user_counties_list'),
    path('user_counties/<str:pk>/',
        UserCountyDetailView.as_view(),
        name='user_county_detail'),

    path('wards/',
        WardView.as_view(),
        name='wards_list'),
    path('wards/<str:pk>/',
        cache_page(60*60*12)(WardDetailView.as_view()),
        name='ward_detail'),
    path('wards/slim_detail/<str:pk>/',
        cache_page(60*60*12)(WardSlimDetailView.as_view()),
        name='ward_slim_detail'),

    path('towns/', TownListView.as_view(), name='towns_list'),
    path('towns/<str:pk>/', TownDetailView.as_view(),
        name='town_detail'),

    path('constituencies/',
        ConstituencyView.as_view(),
        name='constituencies_list'),
    path('constituencies/<str:pk>/',
        cache_page(60*60*12)(ConstituencyDetailView.as_view()),
        name='constituency_detail'),
    path('constituencies/slim_detail/<str:pk>/',
        cache_page(60*60*12)(ConstituencySlimDetailView.as_view()),
        name='constituency_slim_detail'),

    path('address/', PhysicalAddressView.as_view(),
        name='physical_addresses_list'),
    path('address/<str:pk>/',
        PhysicalAddressDetailView.as_view(),
        name='physical_address_detail'),

    path('filtering_summaries/',
        FilteringSummariesView.as_view(), name="filtering_summaries"),

    path('documents/', DocumentUploadListView.as_view(), name='documents'),
    re_path(r'^documents/(?P<pk>[a-z0-9\-]+)/$',
        DocumentUploadDetailView.as_view(), name='document_detail'),
)
