# Generated by Django 4.2.7 on 2025-04-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('admin_offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOfficeContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.contact')),
                ('admin_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='admin_offices.adminoffice')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
            bases=('common.contact',),
        ),
        migrations.AddField(
            model_name='adminoffice',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.constituency'),
        ),
        migrations.AddField(
            model_name='adminoffice',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.county'),
        ),
    ]
