name: CI-Prod

on:
  push:
    branches: [ mfr-api-prod ]


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master  
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_KEY }}
        script: |
          set -e
          cd /opt/mfl_api
          if ! [[ -d './.git' ]]; then git init; fi
          if ! [[ `git remote -v | awk '{print $1}' | head -n 1` =~ 'origin' ]]; then git remote add origin ${{ github.server_url }}${{ github.username }}/${{ github.repository }}.git; fi
          git stash
          git pull origin mfr-api-prod
          echo ${{ secrets.SERVER_KEY }} | sudo -S service supervisor restart
          

          
          
  

        