name: CI

on:
  push:
    branches: [ main ]


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Build Dependencies
      run : yarn global add pm2; yarn global add pnpm
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master  
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_KEY }}
        script: |
          set -e
          cd /opt/mfl_api_testing_clone_prod
          if ! [[ -d './.git' ]]; then git init; fi
          if ! [[ `git remote -v | awk '{print $1}' | head -n 1` =~ 'origin' ]]; then git remote add origin ${{ github.server_url }}${{ github.username }}/${{ github.repository }}.git; fi
          git stash
          git pull origin main
          sudo service supervisor restart
          

          
          
  

        